# Use the PHP environment
language: php

# Trigger only on master -- we'll add Github pull requests in settings
branches:
  only:
    - master
script:
  - zip -r build ./src/*
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build.zip
  skip_cleanup: true
  on:
    tags: true